version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  hibernate-test:
    build:
      context: .
      dockerfile: Dockerfile-hibernate-test
    container_name: hibernate_test_container
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    restart: "no"

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
