-- Drop таблицы с зависимостями
DROP TABLE IF EXISTS play_list_type CASCADE;
DROP TABLE IF EXISTS viewed_movies CASCADE;
DROP TABLE IF EXISTS playlist_film CASCADE;
DROP TABLE IF EXISTS director_film CASCADE;
DROP TABLE IF EXISTS genre_film CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;

-- Drop остальные таблицы
DROP TABLE IF EXISTS type CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS director CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS film CASCADE;
